[
  {
      "name": "A Thousand Floating Dreams",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "Elemental Mastery",
      "passiveName": "A Thousand Nights' Dawnsong",
      "passiveDesc": "Party members other than the equipping character will provide the equipping character with buffs based on whether their Elemental Type is the same as the latter or not. If their Elemental Types are the same, increase Elemental Mastery by 32. If not, increase the equipping character's DMG Bonus from their Elemental Type by 10%. Each of the aforementioned effects can have up to 3 stacks. Additionally, all nearby party members other than the equipping character will have their Elemental Mastery increased by 40. Multiple such effects from multiple such weapons can stack.",
      "location": "Gacha",
      "ascensionMaterial": "oasis",
      "id": "a-thousand-floating-dreams"
  },
  {
      "name": "Akuoumaru",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Watatsumi Wavewalker",
      "passiveDesc": "For every point of the entire party's combined maximum Energy capacity, the Elemental Burst DMG of the character equipping this weapon is increased by 0.12/0.15/0.18/0.21/0.24%. A maximum of 40/50/60/70/80% increased Elemental Burst DMG can be achieved this way.",
      "location": "Gacha",
      "ascensionMaterial": "distantant-sea",
      "id": "akuoumaru"
  },
  {
      "name": "Alley Hunter",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "Attack",
      "passiveName": "Urban Guerrilla",
      "passiveDesc": "Every 4s a character is on the field, their ATK increases by 4/5/6/7/8% and their CRIT DMG increases by 4/5/6/7/8%. This effect has a maximum of 5 stacks and will not be reset if the character leaves the field, but will be cleared when the character takes DMG.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "alley-hunter"
  },
  {
      "name": "Amber Catalyst",
      "type": "Catalyst",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "Elemental Mastery",
      "passiveName": "Elemental Mastery",
      "passiveDesc": "Normal Attack hits increase all Elemental DMG by 6/7.5/9/10.5/12% for 6s. Max 2 stacks.",
      "location": "Chests",
      "ascensionMaterial": "aerosiderite",
      "id": "amber-catalyst"
  },
  {
      "name": "Amenoma Kageuchi",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "ATK",
      "passiveName": "Iwakura Succession",
      "passiveDesc": "After casting an Elemental Skill, gain 1 Succession Seed. This effect can be triggered once every 5s. The Succession Seed lasts for 30s. Up to 3 Succession Seeds may exist simultaneously. After using an Elemental Burst, all Succession Seeds are consumed and after 2s, the character regenerates 6/7.5/9/10.5/12 Energy for each seed consumed.",
      "location": "Crafting",
      "ascensionMaterial": "distantant-sea",
      "id": "amenoma-kageuchi"
  },
  {
      "name": "Amos' Bow",
      "type": "Bow",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "ATK",
      "passiveName": "Strong-Willed",
      "passiveDesc": "Increases Normal Attack and Aimed Shot DMG by 12/15/18/21/24%. Increases DMG from arrows shot by a further 8/10/12/14/16% for every 0.1s that the arrow is in flight, up to 0.5s. Stacks up to 5 times on each arrow.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "amos-bow"
  },
  {
      "name": "Apprentice's Notes",
      "type": "Catalyst",
      "rarity": 1,
      "baseAttack": 23,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "decarabian",
      "id": "apprentice-s-notes"
  },
  {
      "name": "Aqua Simulacra",
      "type": "Bow",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "CRIT DMG",
      "passiveName": "The Cleansing Form",
      "passiveDesc": "HP is increased by 16%. When there are opponents nearby, the DMG dealt by the wielder of this weapon is increased by 20%. This will take effect whether the character is on-field or not.",
      "location": "Gacha",
      "ascensionMaterial": "Luminous Sands from Guyun",
      "id": "aqua-simulacra"
  },
  {
      "name": "Aquila Favonia",
      "type": "Sword",
      "rarity": 5,
      "baseAttack": 48,
      "subStat": "Physical DMG Bonus",
      "passiveName": "Falcon's Defiance",
      "passiveDesc": "ATK is increased by 20/25/30/35/40%. Triggers on taking DMG: the soul of the Falcon of the West awakens, holding the banner of the resistance aloft, regenerating HP equal to 100/115/130/145/160% of ATK and dealing 200/230/260/290/320% of ATK as DMG to surrounding enemies. This effect can only occur once every 15s.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "aquila-favonia"
  },
  {
      "name": "Ballad of the Boundless Blue",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Energy Recharge",
      "passiveName": "Azure Skies",
      "passiveDesc": "Within 6s after Normal or Charged Attacks hit an opponent, Normal Attack DMG will be increased by 8/10/12/14/16% and Charged Attack DMG will be increased by 6/7.5/9/10.5/12%. Max 3 stacks. This effect can be triggered once every 0.3s.",
      "location": "Event: Waterborne Poetry",
      "ascensionMaterial": "boreal",
      "id": "ballad-of-the-boundless-blue"
  },
  {
      "name": "Ballad Of The Fjords",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT Rate",
      "passiveName": "Tales of the Tundra",
      "passiveDesc": "When there are at least 3 different Elemental Types in your party, Elemental Mastery will be increased by 120.",
      "location": "BP Bounty",
      "ascensionMaterial": "Goblet Of The Pristine Sea",
      "id": "ballad-of-the-fjords"
  },
  {
      "name": "Beacon of the Reed Sea",
      "type": "Claymore",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "CRIT Rate",
      "passiveName": "Desert Watch",
      "passiveDesc": "After the character's Elemental Skill hits an opponent, their ATK will be increased by 20% for 8s. After the character takes DMG, their ATK will be increased by 20% for 8s. The 2 aforementioned effects can be triggered even when the character is not on the field. Additionally, when not protected by a shield, the character's Max HP will be increased by 32%.",
      "location": "Gacha",
      "ascensionMaterial": "Echo of Scorching Might",
      "id": "beacon-of-the-reed-sea"
  },
  {
      "name": "Beginner's Protector",
      "type": "Polearm",
      "rarity": 1,
      "baseAttack": 23,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "dandelion",
      "id": "beginner-s-protector"
  },
  {
      "name": "Black Tassel",
      "type": "Polearm",
      "rarity": 3,
      "baseAttack": 38,
      "subStat": "HP",
      "passiveName": "Bane of the Soft",
      "passiveDesc": "Increases DMG against slimes by 40/50/60/70/80%.",
      "location": "Gacha",
      "ascensionMaterial": "guyun",
      "id": "black-tassel"
  },
  {
      "name": "Blackcliff Agate",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT DMG",
      "passiveName": "Press the Advantage",
      "passiveDesc": "After defeating an opponent, ATK is increased by 12% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "guyun",
      "id": "blackcliff-agate"
  },
  {
      "name": "Blackcliff Agate",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT DMG",
      "passiveName": "Press the Advantage",
      "passiveDesc": "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "guyun",
      "id": "blackcliff-amulet"
  },
  {
      "name": "Blackcliff Longsword",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "CRIT DMG",
      "passiveName": "Press the Advantage",
      "passiveDesc": "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "guyun",
      "id": "blackcliff-longsword"
  },
  {
      "name": "Blackcliff Pole",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT DMG",
      "passiveName": "Press the Advantage",
      "passiveDesc": "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "elixir",
      "id": "blackcliff-pole"
  },
  {
      "name": "Blackcliff Slasher",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT DMG",
      "passiveName": "Press the Advantage",
      "passiveDesc": "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "elixir",
      "id": "blackcliff-slasher"
  },
  {
      "name": "Blackcliff Warbow",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "CRIT DMG",
      "passiveName": "Press the Advantage",
      "passiveDesc": "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "guyun",
      "id": "blackcliff-warbow"
  },
  {
      "name": "Bloodtainted Greatsword",
      "type": "Claymore",
      "rarity": 3,
      "baseAttack": 38,
      "subStat": "Elemental Mastery",
      "passiveName": "Bane of Fire and Thunder",
      "passiveDesc": "Increases DMG against enemies affected by Pyro or Electro by 12/15/18/21/24%.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "bloodtainted-greatsword"
  },
  {
      "name": "Calamity Queller",
      "type": "Polearm",
      "rarity": 5,
      "baseAttack": 49,
      "subStat": "ATK",
      "passiveName": "Extinguishing Precept",
      "passiveDesc": "Gain 12/15/18/21/24% All Elemental DMG Bonus. Obtain Consummation for 20s after using an Elemental Skill, causing ATK to increase by 3.2/4/4.8/5.6/6.4% per second. This ATK increase has a maximum of 6 stacks. When the character equipped with this weapon is not on the field, Consummation's ATK increase is doubled.",
      "location": "Gacha",
      "ascensionMaterial": "elixir",
      "id": "calamity-queller"
  },
  {
      "name": "Cashflow Supervision",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 48,
      "subStat": "CRIT Rate",
      "passiveName": "Golden Blood-Tide",
      "passiveDesc": "ATK is increased by 16/20/24/28/32%. When current HP increases or decreases, Normal Attack DMG will be increased by 16/20/24/28/32% and Charged Attack DMG will be increased by 14/17.5/21/24.5/28% for 4s. Max 3 stacks. This effect can be triggered once every 0.3s. When the wielder has 3 stacks, ATK SPD will be increased by 8/10/12/14/16%.",
      "location": "Gacha",
      "ascensionMaterial": "pristine-sea",
      "id": "cashflow-supervision"
  },
  {
      "name": "Cinnabar Spindle",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "DEF",
      "passiveName": "Spotless Heart",
      "passiveDesc": "Elemental Skill DMG is increased by 40/50/60/70/80% of DEF. The effect will be triggered no more than once every 1.5s and will be cleared 0.1s after the Elemental Skill deals DMG.",
      "location": "Shadows Amidst Snowstorms Event",
      "ascensionMaterial": "decarabian",
      "id": "cinnabar-spindle"
  },
  {
      "name": "Compound Bow",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "Physical DMG Bonus",
      "passiveName": "Infusion Arrow",
      "passiveDesc": "Normal Attack and Aimed Shot hits increase ATK by 4/5/6/7/8% and Normal Attack SPD by 1.2/1.5/1.8/2.1/2.4% for 6s. Max 4 stacks. Can only occur once every 0.3s.",
      "location": "Crafting",
      "ascensionMaterial": "aerosiderite",
      "id": "compound-bow"
  },
  {
      "name": "Cool Steel",
      "type": "Sword",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "ATK",
      "passiveName": "Bane of Water and Ice",
      "passiveDesc": "Increases DMG against enemies affected by Hydro or Cryo by 12/15/18/21/24%.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "cool-steel"
  },
  {
      "name": "Crane's Echoing Call",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 49,
      "subStat": "ATK",
      "passiveName": "Cloudfall Axiom",
      "passiveDesc": "After the equipping character hits an opponent with a Plunging Attack, all nearby party members' Plunging Attacks will deal 28% increased DMG for 20s. When nearby party members hit opponents with Plunging Attacks, they will restore 2.5/2.75/3/3.25/3.5 Energy to the equipping character. Energy can restored this way every 0.7s. This energy regain effect can be triggered even if the equipping character is not on the field.",
      "location": "Gacha",
      "ascensionMaterial": "elixir",
      "id": "crane-s-echoing-call"
  },
  {
      "name": "Crescent Pike",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Physical DMG Bonus",
      "passiveName": "Infusion Needle",
      "passiveDesc": "After picking up an Elemental Orb/Particle, Normal and Charged Attacks deal an additional 20% ATK as DMG for 5s.",
      "location": "Crafting",
      "ascensionMaterial": "guyun",
      "id": "crescent-pike"
  },
  {
      "name": "Crimson Moon's Semblance",
      "type": "Polearm",
      "rarity": 5,
      "baseAttack": 48,
      "subStat": "CRIT Rate",
      "passiveName": "Ashen Sun's Shadow",
      "passiveDesc": "Grants a Bond of Life equal to 25% of Max HP when a Charged Attack hits an opponent. This effect can be triggered up to once every 14s. In addition, when the equipping character has a Bond of Life, they gain a 12/16/20/24/28% DMG Bonus; if the value of the Bond of Life is greater than or equal to 30% of Max HP, then gain an additional 24/32/40/48/56% DMG",
      "location": "Gacha",
      "ascensionMaterial": "pristine-sea",
      "id": "crimson-moon-s-semblance"
  },
  {
      "name": "Dark Iron Sword",
      "type": "Sword",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "Elemental Mastery",
      "passiveName": "Overloaded",
      "passiveDesc": "Upon causing an Overloaded, Superconduct, Electro-Charged, or an Electro-infused Swirl reaction, increases Base ATK by 20/25/30/35/40% for 12s.",
      "location": "Talk to Chen the Sharp",
      "ascensionMaterial": "guyun",
      "id": "dark-iron-sword"
  },
  {
      "name": "Deathmatch",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "CRIT Rate",
      "passiveName": "Gladiator",
      "passiveDesc": "If there are at least 2 opponents nearby, ATK is increased by 16% and DEF is increased by 16%. If there are less than 2 enemies nearby, ATK is increased by 24%.",
      "location": "BP Bounty",
      "ascensionMaterial": "boreal",
      "id": "deathmatch"
  },
  {
      "name": "Debate Club",
      "type": "Claymore",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "ATK",
      "passiveName": "Blunt Conclusion",
      "passiveDesc": "After using an Elemental Skill, Normal or Charged Attacks, on hit, deal an additional 60/75/90/105/120% ATK DMG in a small area. Effect lasts 15s. DMG can only occur once every 3s.",
      "location": "Gacha",
      "ascensionMaterial": "elixir",
      "id": "debate-club"
  },
  {
      "name": "Dialogues of the Desert Sages",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "HP",
      "passiveName": "Principle of Equilibrium",
      "passiveDesc": "When the wielder performs healing, restore 8 Energy. This effect can be triggered once every 10s and can occur even when the character is not on the field.",
      "location": "Event: Alchemical Ascension",
      "ascensionMaterial": "talisman",
      "id": "dialogues-of-the-desert-sages"
  },
  {
      "name": "Dodoco Tales",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "ATK",
      "passiveName": "Dodoventure!",
      "passiveDesc": "Normal Attack hits on opponents increase Charged Attack DMG by 16/20/24/28/32% for 6s. Charged Attack hits on opponents increase ATK by 8/10/12/14/16% for 6s.",
      "location": "Midsummer Island Adventure Event",
      "ascensionMaterial": "boreal",
      "id": "dodoco-tales"
  },
  {
      "name": "Dragon's Bane",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "Elemental Mastery",
      "passiveName": "Bane of Flame and Water",
      "passiveDesc": "Increases DMG against enemies affected by Hydro or Pyro by 20/24/28/32/36%.",
      "location": "Gacha",
      "ascensionMaterial": "elixir",
      "id": "dragon-s-bane"
  },
  {
      "name": "Dragonspine Spear",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "Physical DMG Bonus",
      "passiveName": "Frost Burial",
      "passiveDesc": "Hitting an opponent with Normal and Charged Attacks has a 60% chance of forming and dropping an Everfrost Icicle above them, dealing 80% AoE ATK DMG. Opponents affected by Cryo are dealt 200% ATK DMG. Can only occur once every 10s.",
      "location": "Crafting",
      "ascensionMaterial": "elixir",
      "id": "dragonspine-spear"
  },
  {
      "name": "Dull Blade",
      "type": "Sword",
      "rarity": 1,
      "baseAttack": 23,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "decarabian",
      "id": "dull-blade"
  },
  {
      "name": "Ebony Bow",
      "type": "Bow",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "ATK",
      "passiveName": "Decimate",
      "passiveDesc": "Increases DMG against mechanoid Ruin enemies by 40/50/60/70/80%.",
      "location": "Chests",
      "ascensionMaterial": "",
      "id": "ebony-bow"
  },
  {
      "name": "Elegy for the End",
      "type": "Bow",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "Energy Recharge",
      "passiveName": "The Parting Refrain!",
      "passiveDesc": "A part of the 'Millennial Movement' that wanders amidst the winds. Increases Elemental Mastery by 60. When the Elemental Skills or Elemental Bursts of the character wielding this weapon hit opponents, that character gains a Sigil of Remembrance. This effect can be triggered once every 0.2s and can be triggered even if said character is not on the field. When you possess 4 Sigils of Remembrance, all of them will be consumed and all nearby party members will obtain the 'Millennial Movement: Farewell Song' effect for 12s. 'Millennial Movement: Farewell Song' increases Elemental Mastery by 100 and increases ATK by 20%. Once this effect is triggered, you will not gain Sigils of Remembrance for 20s. Of the many effects of the 'Millennial Movement,' buffs of the same type will not stack.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "elegy-for-the-end"
  },
  {
      "name": "Emerald Orb",
      "type": "Catalyst",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "Elemental Mastery",
      "passiveName": "Rapids",
      "passiveDesc": "Upon causing a Vaporize, Electro-Charged, Frozen, or a Hydro-infused Swirl reaction, increases Base ATK by 20/25/30/35/40% for 12s.",
      "location": "Gacha",
      "ascensionMaterial": "guyun",
      "id": "emerald-orb"
  },
  {
      "name": "End of the Line",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Net Snapper",
      "passiveDesc": "Triggers the Flowrider effect after using an Elemental Skill, dealing 80% ATK as AoE DMG upon hitting an opponent with an attack. Flowrider will be removed after 15s or after causing 3 instances of AoE DMG. Only 1 instance of AoE DMG can be caused every 2s in this way. Flowrider can be triggered once every 12s.",
      "location": "Sumeru Fishing Association",
      "ascensionMaterial": "scorching",
      "id": "end-of-the-line"
  },
  {
      "name": "Engulfing Lightning",
      "type": "Polearm",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "Energy Recharge",
      "passiveName": "Timeless Dream: Eternal Stove",
      "passiveDesc": "ATK increased by 28/35/42/49/56% of Energy Recharge over the base 100%. You can gain a maximum bonus of 80/90/100/110/120% ATK. Gain 30/35/40/45/50% Energy Recharge for 12s after using an Elemental Burst.",
      "location": "Gacha",
      "ascensionMaterial": "mask",
      "id": "engulfing-lightning"
  },
  {
      "name": "Everlasting Moonglow",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "HP",
      "passiveName": "Byakuya Kougetsu",
      "passiveDesc": "Healing Bonus increased by 10/12.5/15/17.5/20%, Normal Attack DMG is increased by 1/1.5/2/2.5/3% of the Max HP of the character equipping this weapon. For 12s after using an Elemental Burst, Normal Attacks that hit opponents will restore 0.6 Energy. Energy can be restored this way once every 0.1s.",
      "location": "Gacha",
      "ascensionMaterial": "distantant-sea",
      "id": "everlasting-moonglow"
  },
  {
      "name": "Eye of Perception",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "ATK",
      "passiveName": "Echo",
      "passiveDesc": "Normal and Charged Attacks have a 50% chance to fire a Bolt of Perception, dealing 240/270/300/330/360% ATK as DMG. This bolt can bounce between enemies a maximum of 4 times. This effect can occur once every 12/11/10/9/8s.",
      "location": "Gacha",
      "ascensionMaterial": "elixir",
      "id": "eye-of-perception"
  },
  {
      "name": "Fading Twilight",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Radiance of the Deeps",
      "passiveDesc": "Has three states, Evengleam, Afterglow, and Dawnblaze, which increase DMG dealt from 6%/10%/14% (R1) to 12%/20%/28% (R5) respectively. When attacks hit opponents, this weapon will switch to the next state. This weapon can change states once every 7s. The character equipping this weapon can still trigger the state switch while not on the field.",
      "location": "Event: Perilous Trail",
      "ascensionMaterial": "aerosiderite",
      "id": "fading-twilight"
  },
  {
      "name": "Favonius Codex",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Windfall",
      "passiveDesc": "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "favonius-codex"
  },
  {
      "name": "Favonius Greatsword",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "Energy Recharge",
      "passiveName": "Windfall",
      "passiveDesc": "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "favonius-greatsword"
  },
  {
      "name": "Favonius Lance",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Energy Recharge",
      "passiveName": "Windfall",
      "passiveDesc": "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "favonius-lance"
  },
  {
      "name": "Favonius Sword",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "Energy Recharge",
      "passiveName": "Windfall",
      "passiveDesc": "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "favonius-sword"
  },
  {
      "name": "Favonius Warbow",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "Energy Recharge",
      "passiveName": "Windfall",
      "passiveDesc": "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "favonius-warbow"
  },
  {
      "name": "Ferrous Shadow",
      "type": "Claymore",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "HP",
      "passiveName": "Unbending",
      "passiveDesc": "When HP falls below 70/75/80/85/90%, increases Charged Attack DMG by 30/35/40/45/50%, and Charged Attacks become much harder to interrupt.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "ferrous-shadow"
  },
  {
      "name": "Festering Desire",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "",
      "passiveDesc": "Increases Elemental Skill DMG by 16/20/24/28/32% and Elemental Skill CRIT Rate by 6/7.5/9/10.5/12%.",
      "location": "Story Quest",
      "ascensionMaterial": "dandelion",
      "id": "festering-desire"
  },
  {
      "name": "Fillet Blade",
      "type": "Sword",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "ATK",
      "passiveName": "Gash",
      "passiveDesc": "On hit, has 50% chance to deal 240/280/320/360/400% ATK DMG to a single enemy. Can only occur once every 15/14/13/12/11s.",
      "location": "Chests",
      "ascensionMaterial": "elixir",
      "id": "fillet-blade"
  },
  {
      "name": "Finale Of The Deep",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "An End Sublime",
      "passiveDesc": "When using an Elemental Skill, ATK will be increased by 12% for 15s, and a Bond of Life worth 25% of Max HP will be granted. This effect can be triggered once every 10s. When the Bond of Life is cleared, a maximum of 150 ATK will be gained based on 2.4% of the Bond when cleared for 15s. Bond of Life: Absorbs healing for the character based on its base value, and clears after healing equal to this value is obtained.",
      "location": "BP Bounty",
      "ascensionMaterial": "Dross Of Pure Sacred Dewdrop",
      "id": "finale-of-the-deep"
  },
  {
      "name": "Fleuve Cendre Ferryman",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Ironbone",
      "passiveDesc": "Increases Elemental Skill CRIT Rate by 8%. Additionally, increases Energy Recharge by 16% for 5s after using an Elemental Skill.s",
      "location": "Fontaine Fishing Association",
      "ascensionMaterial": "Fragment Of An Ancient Chord",
      "id": "fleuve-cendre-ferryman"
  },
  {
      "name": "Flowing Purity",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "Unfinished Masterpiece",
      "passiveDesc": "When using an Elemental Skill, All Elemental DMG Bonus will be increased by 8% for 15s, and a Bond of Life worth 24% of Max HP will be granted. This effect can be triggered once every 10s. When the Bond of Life is cleared, every 1,000 HP cleared in the process will provide 2% All Elemental DMG Bonus. Up to a maximum of 12% All Elemental DMG can be gained this way. This effect lasts 15s. Bond of Life: Absorbs healing for the character based on its base value, and clears after healing equal to this value is obtained.",
      "location": "BP Bounty",
      "ascensionMaterial": "Dross Of Pure Sacred Dewdrop",
      "id": "flowing-purity"
  },
  {
      "name": "Forest Regalia",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Energy Recharge",
      "passiveName": "Forest Sanctuary",
      "passiveDesc": "After triggering Burning, Quicken, Aggravate, Spread, Bloom, Hyperbloom, or Burgeon, a Leaf of Consciousness will be created around the character for a maximum of 10s. When picked up, the Leaf will grant the character 60 Elemental Mastery for 12s. Only 1 Leaf can be generated this way every 20s. This effect can still be triggered if the character is not on the field. The Leaf of Consciousness' effect cannot stack.",
      "location": "Crafting",
      "ascensionMaterial": "talisman",
      "id": "forest-regalia"
  },
  {
      "name": "Freedom-Sworn",
      "type": "Sword",
      "rarity": 5,
      "BaseAttack": 46,
      "subStat": "Elemental Mastery",
      "passiveName": "Revolutionary Chorale",
      "passiveDesc": "A part of the \"Millennial Movement\" that wanders amidst the winds. Increases DMG by 10%/12.5%/15%/17.5%/20%. When the character wielding this weapon triggers Elemental Reactions, they gain a Sigil of Rebellion. This effect can be triggered once every 0.5s and can be triggered even if said character is not on the field.When you possess 2 Sigils of Rebellion, all of them will be consumed and all nearby party members will obtain \"Millennial Movement: Song of Resistance\" for 12s. \"Millennial Movement: Song of Resistance\" increases Normal, Charged, and Plunging Attack DMG by 16%/20%/24%/28%/32% and increases ATK by 20%/25%/30%/35%/40%. Once this effect is triggered, you will not gain Sigils of Rebellion for 20s.Of the many effects of the \"Millennial Movement,\" buffs of the same type will not stack.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "freedom-sworn"
  },
  {
      "name": "Frostbearer",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "",
      "passiveDesc": "Hitting an opponent with Normal and Charged Attacks has a 60% chance of forming and dropping an Everfrost Icicle above them, dealing 80% AoE ATK DMG. Opponents affected by Cryo are dealt 200% ATK DMG. Can only occur once every 10s.",
      "location": "Crafting",
      "ascensionMaterial": "dandelion",
      "id": "frostbearer"
  },
  {
      "name": "Fruit of Fulfillment",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Full Circle",
      "passiveDesc": "Obtain the 'Wax and Wane' effect after an Elemental Reaction is triggered, gaining 24 Elemental Mastery while losing 5% ATK. For every 0.3s, 1 stack of Wax and Wane can be gained. Max 5 stacks. For every 6s that go by without an Elemental Reaction being triggered, 1 stack will be lost. This effect can be triggered even when the character is off-field.",
      "location": "Crafting",
      "ascensionMaterial": "oasis",
      "id": "fruit-of-fulfillment"
  },
  {
      "name": "Hakushin Ring",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Energy Recharge",
      "passiveName": "Sakura Saiguu",
      "passiveDesc": "After the character equipped with this weapon triggers an Electro elemental reaction, nearby party members of an Elemental Type involved in the elemental reaction receive a 10/12.5/15/17.5/20% Elemental DMG Bonus for their element, lasting 6s. Elemental Bonuses gained in this way cannot be stacked.",
      "location": "Crafting",
      "ascensionMaterial": "distantant-sea",
      "id": "hakushin-ring"
  },
  {
      "name": "Halberd",
      "type": "Polearm",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "ATK",
      "passiveName": "Heavy",
      "passiveDesc": "Normal Attacks deal an additional 160/200/240/280/320% DMG. Can only occur once every 10s.",
      "location": "Chests",
      "ascensionMaterial": "elixir",
      "id": "halberd"
  },
  {
      "name": "Hamayumi",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "ATK",
      "passiveName": "Full Draw",
      "passiveDesc": "Increases Normal Attack DMG by 16/20/24/28/32% and Charged Attack DMG by 12/15/18/21/24%. When the equipping character's Energy reaches 100%, this effect is increased by 100%.",
      "location": "Crafting",
      "ascensionMaterial": "narukami",
      "id": "hamayumi"
  },
  {
      "name": "Haran Geppaku Futsu",
      "type": "Sword",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "CRIT Rate",
      "passiveName": "Honed Flow",
      "passiveDesc": "Obtain 12/15/18/21/24% All Elemental DMG Bonus. When other nearby party members use Elemental Skills, the character equipping this weapon will gain 1 Wavespike stack. Max 2 stacks. This effect can be triggered once every 0.3s. When the character equipping this weapon uses an Elemental Skill, all stacks of Wavespike will be consumed to gain Rippling Upheaval: each stack of Wavespike consumed will increase Normal Attack DMG by 20/25/30/35/40% for 8s.",
      "location": "Gacha",
      "ascensionMaterial": "narukami",
      "id": "haran-geppaku-futsu"
  },
  {
      "name": "Harbinger of Dawn",
      "type": "Sword",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "CRIT DMG",
      "passiveName": "Vigorous",
      "passiveDesc": "When HP is above 90%, increases CRIT Rate by 14/18/22/24/28%.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "harbinger-of-dawn"
  },
  {
      "name": "Hunter's Bow",
      "type": "Bow",
      "rarity": 1,
      "baseAttack": 23,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "boreal",
      "id": "hunter-s-bow"
  },
  {
      "name": "Hunter's Path",
      "type": "Bow",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "CRIT Rate",
      "passiveName": "At the End of the Beast-Paths",
      "passiveDesc": "Gain 12% All Elemental DMG Bonus. Obtain the Tireless Hunt effect after hitting an opponent with a Charged Attack. This effect increases Charged Attack DMG by 160% of Elemental Mastery. This effect will be removed after 12 Charged Attacks or 10s. Only 1 instance of Tireless Hunt can be gained every 12s.",
      "location": "Gacha Banner",
      "ascensionMaterial": "Echo of Scorching Might",
      "id": "hunter-s-path"
  },
  {
      "name": "Ibis Piercer",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "Secret Wisdom's Favor",
      "passiveDesc": "The character's Elemental Mastery will increase by 40/50/60/70/80 within 6s after Charged Attacks hit opponents. Max 2 stacks. This effect can triggered once every 0.5s.",
      "location": "Event: Duel! The Summoners' Summit!",
      "ascensionMaterial": "talisman",
      "id": "ibis-piercer"
  },
  {
      "name": "Iron Point",
      "type": "Polearm",
      "rarity": 2,
      "baseAttack": 33,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "dandelion",
      "id": "iron-point"
  },
  {
      "name": "Iron Sting",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Elemental Mastery",
      "passiveName": "Infusion Stinger",
      "passiveDesc": "Dealing Elemental DMG increases all DMG by 6% for 6s. Max 2 stacks. Can only occur once every 1s.",
      "location": "Crafting",
      "ascensionMaterial": "aerosiderite",
      "id": "iron-sting"
  },
  {
      "name": "Jadefall's Splendor",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "HP",
      "passiveName": "Primordial Jade Regalia",
      "passiveDesc": "For 3s after using an Elemental Burst or creating a shield, the equipping character can gain the Primordial Jade Regalia effect: Restore 4.5/5/5.5/6/6.5 Energy every 2.5s, and gain 0.3/0.5/0.7/0.9/1.1% Elemental DMG Bonus for their corresponding Elemental Type for every 1,000 Max HP they possess, up to 12/20/28/36/44%. Primordial Jade Regalia will still take effect even if the equipping character is not on the field.",
      "location": "Gacha",
      "ascensionMaterial": "guyun",
      "id": "jadefall-s-splendor"
  },
  {
      "name": "Kagotsurube Isshin",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Isshin Art Clarity",
      "passiveDesc": "When a Normal, Charged, or Plunging Attack hits an opponent, it will whip up a Hewing Gale, dealing AoE DMG equal to 180% of ATK and increasing ATK by 15% for 8s. This effect can be triggered once every 8s.",
      "location": "Quest: Ere the End, a Glance Back",
      "ascensionMaterial": "mask",
      "id": "kagotsurube-isshin"
  },
  {
      "name": "Kagura's Verity",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "CRIT DMG",
      "passiveName": "Kagura Dance of the Sacred Sakura",
      "passiveDesc": "Gains the Kagura Dance effect when using an Elemental Skill, causing the Elemental Skill DMG of the character wielding this weapon to increase by 12/15/18/21/24% for 16s. Max 3 stacks. This character will gain 12/15/18/21/24% All Elemental DMG Bonus when they possess 3 stacks.",
      "location": "Gacha",
      "ascensionMaterial": "mask",
      "id": "kagura-s-verity"
  },
  {
      "name": "Katsuragikiri Nagamasa",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Samurai Conduct",
      "passiveDesc": "Increases Elemental Skill DMG by 6/7.5/9/10.5/12%. After Elemental Skill hits an opponent, the character loses 3 Energy but regenerates 3/3.5/4/4.5/5 Energy every 2s for the next 6s. This effect can occur once every 10s. Can be triggered even when the character is not on the field.",
      "location": "Crafting",
      "ascensionMaterial": "narukami",
      "id": "katsuragikiri-nagamasa"
  },
  {
      "name": "Key of Khaj-Nisut",
      "type": "Sword",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "HP",
      "passiveName": "Sunken Song of the Sands",
      "passiveDesc": "HP increased by 20%. When an Elemental Skill hits opponents, you gain the Grand Hymn effect for 20s. This effect increases the equipping character's Elemental Mastery by 0.12% of their Max HP. This effect can trigger once every 0.3s. Max 3 stacks. When this effect gains 3 stacks, or when the third stack's duration is refreshed, the Elemental Mastery of all nearby party members will be increased by 0.2% of the equipping character's max HP for 20s.",
      "location": "Gacha",
      "ascensionMaterial": "talisman",
      "id": "key-of-khaj-nisut"
  },
  {
      "name": "King's Squire",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "ATK",
      "passiveName": "Labyrinth Lord's Instruction",
      "passiveDesc": "Obtain the Teachings of the Forest effect when unleashing Elemental Skills and Bursts, increasing Elemental Mastery by 60 for 12s. This effect will be removed when switching characters. When the Teachings of the Forest effect ends or is removed, it will deal 100% of ATK as DMG to 1 nearby opponent. The Teachings of the Forest effect can be triggered once every 20s.",
      "location": "Crafting",
      "ascensionMaterial": "scorching",
      "id": "king-s-squire"
  },
  {
      "name": "Kitain Cross Spear",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Elemental Mastery",
      "passiveName": "Samurai Conduct",
      "passiveDesc": "Increases Elemental Skill DMG by 6/7.5/9/10.5/12%. After Elemental Skill hits an opponent, the character loses 3 Energy but regenerates 3/3.5/4/4.5/5 Energy every 2s for the next 6s. This effect can occur once every 10s. Can be triggered even when the character is not on the field.",
      "location": "Crafting",
      "ascensionMaterial": "mask",
      "id": "kitain-cross-spear"
  },
  {
      "name": "Light of Foliar Incision",
      "type": "Sword",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "CRIT DMG",
      "passiveName": "Whitemoon Bristle",
      "passiveDesc": "CRIT Rate is increased by 4%. After Normal Attacks deal Elemental DMG, the Foliar Incision effect will be obtained, increasing DMG dealt by Normal Attacks and Elemental Skills by 120% of Elemental Mastery.",
      "location": "Gacha",
      "ascensionMaterial": "Copper Talisman of the Forest Dew",
      "id": "light-of-foliar-incision"
  },
  {
      "name": "Lion's Roar",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Bane of Fire and Thunder",
      "passiveDesc": "Increases DMG against enemies affected by Pyro or Electro by 20/24/28/32/36%.",
      "location": "Gacha",
      "ascensionMaterial": "guyun",
      "id": "lion-s-roar"
  },
  {
      "name": "Lithic Blade",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "CRIT DMG",
      "passiveName": "Lithic Axiom - Unity",
      "passiveDesc": "For every character in the party who hails from Liyue, the character who equips this weapon gains 6/7/8/9/10% ATK increase and 2/3/4/5/6% CRIT Rate increase.",
      "location": "Gacha",
      "ascensionMaterial": "guyun",
      "id": "lithic-blade"
  },
  {
      "name": "Lithic Spear",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Lithic Axiom - Unity",
      "passiveDesc": "For every character in the party who hails from Liyue, the character who equips this weapon gains 7/8/9/10/11% ATK increase and a 3/4/5/6/7% CRIT Rate increase. This effect stacks up to 4 times.",
      "location": "Gacha",
      "ascensionMaterial": "aerosiderite",
      "id": "lithic-spear"
  },
  {
      "name": "Lost Prayer to the Sacred Winds",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "CRIT Rate",
      "passiveName": "Boundless Blessing",
      "passiveDesc": "Increases Movement SPD by 10%. When in battle, earn a 6/8/10/12/14% Elemental DMG Bonus every 4s. Max 4 stacks. Lasts until the character falls or leaves combat.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "lost-prayer-to-the-sacred-winds"
  },
  {
      "name": "Luxurious Sea-Lord",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "ATK",
      "passiveName": "Oceanic Victory",
      "passiveDesc": "Increases Elemental Burst DMG by 12/15/18/21/24%. When Elemental Burst hits opponents, there is a 100% chance of summoning a huge onrush of tuna that charges and deals 100/125/150/175/200% ATK as AoE DMG. This effect can occur once every 15s.",
      "location": "Moonlight Merriment Event",
      "ascensionMaterial": "aerosiderite",
      "id": "luxurious-sea-lord"
  },
  {
      "name": "Magic Guide",
      "type": "Catalyst",
      "rarity": 3,
      "baseAttack": 38,
      "subStat": "Elemental Mastery",
      "passiveName": "Bane of Storm and Tide",
      "passiveDesc": "Increases DMG against enemies affected by Hydro or Electro by 12/15/18/21/24%.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "magic-guide"
  },
  {
      "name": "Mailed Flower",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Elemental Mastery",
      "passiveName": "Whispers of Wind and Flower",
      "passiveDesc": "Within 8s after the character's Elemental Skill hits an opponent or the character triggers an Elemental Reaction, their ATK and Elemental Mastery will be increased by 12% and 48 respectively.",
      "location": "Windblume's Breath Event",
      "ascensionMaterial": "Fetters of the Dandelion Gladiator",
      "id": "mailed-flower"
  },
  {
      "name": "Makhaira Aquamarine",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Elemental Mastery",
      "passiveName": "Desert Pavilion",
      "passiveDesc": "The following effect will trigger every 10s: The equipping character will gain 24% of their Elemental Mastery as bonus ATK for 12s, with nearby party members gaining 30% of this buff for the same duration. Multiple instances of this weapon can allow this buff to stack. This effect will still trigger even if the character is not on the field.",
      "location": "Gacha",
      "ascensionMaterial": "scorching",
      "id": "makhaira-aquamarine"
  },
  {
      "name": "Mappa Mare",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Elemental Mastery",
      "passiveName": "Infusion Scroll",
      "passiveDesc": "Triggering an Elemental reaction grants a 8/10/12/14/16% Elemental DMG Bonus for 10s. Max 2 stacks.",
      "location": "Crafting",
      "ascensionMaterial": "aerosiderite",
      "id": "mappa-mare"
  },
  {
      "name": "Memory of Dust",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "ATK",
      "passiveName": "Golden Majesty",
      "passiveDesc": "Increase Shield Strength by 20/25/30/35/40%. Scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.",
      "location": "Gacha",
      "ascensionMaterial": "aerosiderite",
      "id": "memory-of-dust"
  },
  {
      "name": "Messenger",
      "type": "Bow",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "CRIT DMG",
      "passiveName": "Archer's Message",
      "passiveDesc": "Aimed Shot hits on weak spots deal an additional 100/125/150/175/200% ATK DMG as CRIT DMG. Can only occur once every 10s.",
      "location": "Chest",
      "ascensionMaterial": "elixir",
      "id": "messenger"
  },
  {
      "name": "Missive Windspear",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "The Wind Unattained",
      "passiveDesc": "Within 10s after an Elemental Reaction is triggered, ATK is increased by 12/15/18/21/24% and Elemental Mastery is increased by 48/60/72/84/96.",
      "location": "Event: Of Ballads and Brews",
      "ascensionMaterial": "boreal",
      "id": "missive-windspear"
  },
  {
      "name": "Mistsplitter Reforged",
      "type": "Sword",
      "rarity": 5,
      "baseAttack": 48,
      "subStat": "CRIT DMG",
      "passiveName": "Mistsplitter's Edge",
      "passiveDesc": "Gain a 12% Elemental DMG Bonus for every element and receive the might of Mistsplitter's Emblem. At stack levels 1/2/3, Mistsplitter's Emblem provides a 8/16/28% Elemental DMG Bonus for the character's Elemental Type. The character will obtain 1 stack of Mistsplitter's Emblem in each of the following scenarios: Normal Attack deals Elemental DMG (stack lasts 5s), casting Elemental Burst (stack lasts 10s); Energy is less than 100% (stack disappears when Energy is full). Each stack's duration is calculated independently.",
      "location": "Gacha",
      "ascensionMaterial": "distantant-sea",
      "id": "mistsplitter-reforged"
  },
  {
      "name": "Mitternachts Waltz",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Physical DMG Bonus",
      "passiveName": "Evernight Duet",
      "passiveDesc": "Normal Attack hits on opponents increase Elemental Skill DMG by 20/25/30/35/40% for 5s. Elemental Skill hits on opponents increase Normal Attack DMG by 20/25/30/35/40% for 5s.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "mitternachts-waltz"
  },
  {
      "name": "Moonpiercer",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Elemental Mastery",
      "passiveName": "Stillwood Moonshadow",
      "passiveDesc": "After triggering Burning, Quicken, Aggravate, Spread, Bloom, Hyperbloom, or Burgeon, a Leaf of Revival will be created around the character for a maximum of 10s. When picked up, the Leaf will grant the character 16% ATK for 12s. Only 1 Leaf can be generated this way every 20s. This effect can still be triggered if the character is not on the field.",
      "location": "Crafting",
      "ascensionMaterial": "oasis",
      "id": "moonpiercer"
  },
  {
      "name": "Mouun's Moon",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "Watatsumi Wavewalker",
      "passiveDesc": "For every point of the entire party's combined maximum Energy capacity, the Elemental Burst DMG of the character equipping this weapon is increased by 0.12/0.15/0.18/0.21/0.24%. A maximum of 40/50/60/70/80% increased Elemental Burst DMG can be achieved this way.",
      "location": "Gacha",
      "ascensionMaterial": "narukami",
      "id": "mouun-s-moon"
  },
  {
      "name": "Oathsworn Eye",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "People of the Faltering Light",
      "passiveDesc": "Increases Energy Recharge by 24/30/36/42/48% for 10s after using an Elemental Skill.",
      "location": "Three Realms Gateway Offering Event",
      "ascensionMaterial": "distantant-sea",
      "id": "oathsworn-eye"
  },
  {
      "name": "Old Merc's Pal",
      "type": "Claymore",
      "rarity": 2,
      "baseAttack": 33,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "boreal",
      "id": "old-merc-s-pal"
  },
  {
      "name": "Otherworldly Story",
      "type": "Catalyst",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "Energy Recharge",
      "passiveName": "Energy Shower",
      "passiveDesc": "Each Elemental Orb or Particle collected restores 1/1.25/1.5/1.75/2% HP.",
      "location": "Chests",
      "ascensionMaterial": "dandelion",
      "id": "otherworldly-story"
  },
  {
      "name": "Pocket Grimoire",
      "type": "Catalyst",
      "rarity": 2,
      "baseAttack": 33,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "decarabian",
      "id": "pocket-grimoire"
  },
  {
      "name": "Polar Star",
      "type": "Bow",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "CRIT Rate",
      "passiveName": "Daylight's Augury",
      "passiveDesc": "Elemental Skill and Elemental Burst DMG increased by 12/15/18/21/24%. After a Normal Attack, Charged Attack, Elemental Skill or Elemental Burst hits an opponent, 1 stack of Ashen Nightstar will be gained for 12s. When 1/2/3/4 stacks of Ashen Nightstar are present, ATK is increased by (10/12.5/15/17.5/20)/(20/25/30/35/40)/(30/37.5/45/52.5/60)/(48/60/72/84/96)%. The stack of Ashen Nightstar created by the Normal Attack, Charged Attack, Elemental Skill or Elemental Burst will be counted independently of the others.",
      "location": "Gacha",
      "ascensionMaterial": "mask",
      "id": "polar-star"
  },
  {
      "name": "Portable Power Saw",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "HP",
      "passiveName": "Sea Shanty",
      "passiveDesc": "When the wielder is healed or heals others, they will gain a Stoic's Symbol that lasts 30s, up to a maximum of 3 Symbols. When using their Elemental Skill or Burst, all Symbols will be consumed and the Roused effect will be granted for 10s. For each Symbol consumed, gain 40/50/60/70/80 Elemental Mastery, and 2s after the effect occurs, 2/2.5/3/3.5/4 Energy per Symbol consumed will be restored for said character. The Roused effect can be triggered once every 15s, and Symbols can be gained even when the character is not on the field.",
      "location": "Gacha",
      "ascensionMaterial": "pristine-sea",
      "id": "portable-power-saw"
  },
  {
      "name": "Predator",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Strong Strike",
      "passiveDesc": "This weapon's effect is only applied on the following platform(s):'PlayStation Network' Dealing Cryo DMG to opponents increases this character's Normal and Charged Attack DMG by 10% for 6s. This effect can have a maximum of 2 stacks. Additionally, when Aloy equips Predator, ATK is increased by 66.",
      "location": "Given via the Mail on PS4/PS5 between Version 2.1–2.2, obtainable on PC/Mobile via cross save",
      "ascensionMaterial": "narukami",
      "id": "predator"
  },
  {
      "name": "Primordial Jade Cutter",
      "type": "Sword",
      "rarity": 5,
      "BaseAttack": 44,
      "subStat": "CRIT Rate",
      "passiveName": "Protector's Virtue",
      "passiveDesc": "HP increased by 20%/25%/30%/35%/40%. Additionally, provides an ATK Bonus based on 1.2%/1.5%/1.8%/2.1%/2.4% of the wielder's Max HP.",
      "location": "Gacha",
      "ascensionMaterial": "elixir",
      "id": "primordial-jade-cutter"
  },
  {
      "name": "Primordial Jade Winged-Spear",
      "type": "Polearm",
      "rarity": 5,
      "baseAttack": 48,
      "subStat": "CRIT Rate",
      "passiveName": "Eagle Spear of Justice",
      "passiveDesc": "On hit, increases ATK by 3.2/3.9/4.6/5.3/6% for 6s. Max 7 stacks. Can only occur once every 0.3s. Full stacks increase Skill DMG by 12/16/20/24/28%.",
      "location": "Gacha",
      "ascensionMaterial": "guyun",
      "id": "primordial-jade-winged-spear"
  },
  {
      "name": "Prospector's Drill",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "Masons' Ditty",
      "passiveDesc": "When the wielder is healed or heals others, they will gain a Unity's Symbol that lasts 30s, up to a maximum of 3 Symbols. When using their Elemental Skill or Burst, all Symbols will be consumed and the Struggle effect will be granted for 10s. For each Symbol consumed, gain 3/4/5/6/7% ATK and 7/8.5/10/11.5/13% All Elemental DMG Bonus. The Struggle effect can be triggered once every 15s, and Symbols can be gained even when the character is not on the field.",
      "location": "Gacha",
      "ascensionMaterial": "ancient-chord",
      "id": "prospectors-drill"
  },
  {
      "name": "Prototype Amber",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "HP",
      "passiveName": "Gilding",
      "passiveDesc": "Using an Elemental Burst regenerates 4 Energy every 2s for 6s. All party members will regenerate 4% HP every 2s for this duration.",
      "location": "Crafting",
      "ascensionMaterial": "elixir",
      "id": "prototype-amber"
  },
  {
      "name": "Prototype Archaic",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "Crush",
      "passiveDesc": "On hit, Normal or Charged Attacks have a 50% chance to deal an additional 240/300/360/420/480% ATK DMG to enemies within a small radius. Can only occur once every 15s.",
      "location": "Crafting",
      "ascensionMaterial": "aerosiderite",
      "id": "prototype-archaic"
  },
  {
      "name": "Prototype Crescent",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Unreturning",
      "passiveDesc": "Aimed Shot hits on weak points increase Movement SPD by 10% and ATK by 6% for 10s.",
      "location": "Crafting",
      "ascensionMaterial": "elixir",
      "id": "prototype-crescent"
  },
  {
      "name": "Prototype Starglitter",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Magic Affinity",
      "passiveDesc": "After using an Elemental Skill, increases Normal and Charged Attack DMG by 8% for 12s. Max 2 stacks.",
      "location": "Crafting",
      "ascensionMaterial": "aerosiderite",
      "id": "prototype-grudge"
  },
  {
      "name": "Prototype Amber",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "HP",
      "passiveName": "Gilding",
      "passiveDesc": "Using an Elemental Burst regenerates 4/4.5/5/5.5/6 Energy every 2s for 6s. Additionally, all party members will regenerate 4/4.5/5/5.5/6% HP every 2s for this duration.",
      "location": "Crafting",
      "ascensionMaterial": "elixir",
      "id": "prototype-malice"
  },
  {
      "name": "Prototype Rancour",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Physical DMG Bonus",
      "passiveName": "Smashed Stone",
      "passiveDesc": "On hit, Normal or Charged Attacks increase Base ATK and DEF by 4/4.5/5/5.5/6% for 6s. Max 4 stacks. Can only occur once every 0.3s.",
      "location": "Crafting",
      "ascensionMaterial": "elixir",
      "id": "prototype-rancour"
  },
  {
      "name": "Prototype Starglitter",
      "type": "polearm",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Magic Affinity",
      "passiveDesc": "After using an Elemental Skill, increases Normal and Charged Attack DMG by 8% for 12s. Max 2 stacks.",
      "location": "forging",
      "ascensionMaterial": "aerosiderite",
      "id": "prototype-starglitter"
  },
  {
      "name": "Quartz",
      "type": "Claymore",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "Elemental Mastery",
      "passiveName": "Residual Heat",
      "passiveDesc": "Upon causing an Overloaded, Melt, Burning, Vaporize, or a Pyro-infused Swirl reaction, increases Base ATK by 20/25/30/35/40% for 12s.",
      "location": "Chests",
      "ascensionMaterial": "",
      "id": "quartz"
  },
  {
      "name": "Rainslasher",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Elemental Mastery",
      "passiveName": "Bane of Storm and Tide",
      "passiveDesc": "Increases DMG against enemies affected by Hydro or Electro by 20/25/30/35/40%.",
      "location": "Gacha",
      "ascensionMaterial": "elixir",
      "id": "rainslasher"
  },
  {
      "name": "Range Gauge",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "Masons' Ditty",
      "passiveDesc": "When the wielder is healed or heals others, they will gain a Unity's Symbol that lasts 30s, up to a maximum of 3 Symbols. When using their Elemental Skill or Burst, all Symbols will be consumed and the Struggle effect will be granted for 10s. For each Symbol consumed, gain 3/4/5/6/7% ATK and 7/8.5/10/11.5/% All Elemental DMG Bonus. The Struggle effect can be triggered once every 15s, and Symbols can be gained even when the character is not on the field.",
      "location": "Gacha",
      "ascensionMaterial": "ancient-chord",
      "id": "range-gauge"
  },
  {
      "name": "Raven Bow",
      "type": "Bow",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "Elemental Mastery",
      "passiveName": "Bane of Flame and Water",
      "passiveDesc": "Increases DMG against enemies affected by Hydro or Pyro by 12/15/18/21/24%.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "raven-bow"
  },
  {
      "name": "Recurve Bow",
      "type": "Bow",
      "rarity": 3,
      "baseAttack": 38,
      "subStat": "HP",
      "passiveName": "Cull the Weak",
      "passiveDesc": "Defeating an opponent restores 8/10/12/14/16% HP.",
      "location": "Chest",
      "ascensionMaterial": "dandelion",
      "id": "recurve-bow"
  },
  {
      "name": "Redhorn Stonethresher",
      "type": "Claymore",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "CRIT DMG",
      "passiveName": "Gokadaiou Otogibanashi",
      "passiveDesc": "DEF is increased by 28/35/42/49/56%. Normal and Charged Attack DMG is increased by 40/50/60/70/80% of DEF.",
      "location": "Gacha",
      "ascensionMaterial": "narukami",
      "id": "redhorn-stonethresher"
  },
  {
      "name": "Rightful Reward",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "HP",
      "passiveName": "Tip of the Spear",
      "passiveDesc": "When the wielder is healed, restore 8 Energy. This effect can be triggered once every 10s, and can occur even when the character is not on the field.",
      "location": "BP Bounty",
      "ascensionMaterial": "Broken Goblet Of The Pristine Sea",
      "id": "rightful-reward"
  },
  {
      "name": "Royal Bow",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Focus",
      "passiveDesc": "Upon damaging an enemy, increases CRIT Rate by 8%. Max 5 stacks. A CRIT hit removes all stacks.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "dandelion",
      "id": "royal-bow"
  },
  {
      "name": "Royal Greatsword",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 43,
      "subStat": "ATK",
      "passiveName": "Focus",
      "passiveDesc": "Upon damaging an enemy, increases CRIT Rate by 8%. Max 5 stacks. A CRIT hit removes all stacks.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "dandelion",
      "id": "royal-greatsword"
  },
  {
      "name": "Royal Grimoire",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "Focus",
      "passiveDesc": "Upon damaging an enemy, increases CRIT Rate by 8%. Max 5 stacks. A CRIT hit removes all stacks.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "decarabian",
      "id": "royal-grimoire"
  },
  {
      "name": "Royal Longsword",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Focus",
      "passiveDesc": "Upon damaging an enemy, increases CRIT Rate by 8%. Max 5 stacks. A CRIT hit removes all stacks.",
      "location": "Starglitter Exchange",
      "ascensionMaterial": "decarabian",
      "id": "royal-longsword"
  },
  {
      "name": "Royal Spear",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "ATK",
      "passiveName": "Focus",
      "passiveDesc": "Upon damaging an opponent, increases CRIT Rate by 8%. Max 5 stacks. A CRIT Hit removes all stacks.",
      "location": "Starglitter Exchange",
      "id": "royal-spear"
  },
  {
      "name": "Rust",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Rapid Firing",
      "passiveDesc": "Increases Normal Attack DMG by 40/50/60/70/80% but decreases Aimed Shot DMG by 8/9/10/11/12%",
      "location": "Gacha",
      "ascensionMaterial": "guyun",
      "id": "rust"
  },
  {
      "name": "Sacrificial Bow",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Energy Recharge",
      "passiveName": "Composed",
      "passiveDesc": "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "sacrificial-bow"
  },
  {
      "name": "Sacrificial Fragments",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "Elemental Mastery",
      "passiveName": "Composed",
      "passiveDesc": "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "sacrificial-fragments"
  },
  {
      "name": "Sacrificial Greatsword",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Energy Recharge",
      "passiveName": "Composed",
      "passiveDesc": "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "sacrificial-greatsword"
  },
  {
      "name": "Sacrificial Jade",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "CRIT Rate",
      "passiveName": "Jade Circulation",
      "passiveDesc": "When not on the field for more than 5s, Max HP will be increased by 32% and Elemental Mastery will be increased by 40. These effects will be canceled after the wielder has been on the field for 10s.",
      "location": "BP Bounty",
      "ascensionMaterial": "Luminous Sands From Guyun ",
      "id": "sacrificial-jade"
  },
  {
      "name": "Sacrificial Sword",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 41,
      "subStat": "Energy Recharge",
      "passiveName": "Composed",
      "passiveDesc": "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "sacrificial-sword"
  },
  {
      "name": "Sapwood Blade",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Energy Recharge",
      "passiveName": "Forest Sanctuary",
      "passiveDesc": "After triggering Burning, Quicken, Aggravate, Spread, Bloom, Hyperbloom, or Burgeon, a Leaf of Consciousness will be created around the character for a maximum of 10s. When picked up, the Leaf will grant the character 60 Elemental Mastery for 12s. Only 1 Leaf can be generated this way every 20s. This effect can still be triggered if the character is not on the field. The Leaf of Consciousness' effect cannot stack.",
      "location": "Crafting",
      "ascensionMaterial": "talisman",
      "id": "sapwood-blade"
  },
  {
      "name": "Scion Of The Blazing Sun",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "CRIT Rate",
      "passiveName": "The Way of Sunfire",
      "passiveDesc": "After a Charged Attack hits an opponent, a Sunfire Arrow will descend upon the opponent hit, dealing 60% ATK as DMG, and applying the Heartsearer effect to the opponent damaged by said Arrow for 10s. Opponents affected by Heartsearer take 28% more Charged Attack DMG from the wielder. A Sunfire Arrow can be triggered once every 10s.",
      "location": "BP Bounty",
      "ascensionMaterial": "Echo Of Scorching Might",
      "id": "scion-of-the-blazing-sun"
  },
  {
      "name": "Seasoned Hunter's Bow",
      "type": "Bow",
      "rarity": 2,
      "baseAttack": 33,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "boreal",
      "id": "seasoned-hunter-s-bow"
  },
  {
      "name": "Serpent Spine",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT Rate",
      "passiveName": "Wavesplitter",
      "passiveDesc": "Every 4s a character is on the field, they will deal 6% more DMG and take 3% more DMG. This effect has a maximum of 5 stacks and will not be reset if the character leaves the field, but will be cleared when the character takes DMG.",
      "location": "BP Bounty",
      "ascensionMaterial": "aerosiderite",
      "id": "serpent-spine"
  },
  {
      "name": "Sharpshooter's Oath",
      "type": "Bow",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "CRIT DMG",
      "passiveName": "Precise",
      "passiveDesc": "Increases DMG against weak spots by 24/30/36/42/48%.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "sharpshooter-s-oath"
  },
  {
      "name": "Silver Sword",
      "type": "Sword",
      "rarity": 2,
      "baseAttack": 33,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "decarabian",
      "id": "silver-sword"
  },
  {
      "name": "Skyrider Greatsword",
      "type": "Claymore",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "Physical DMG Bonus",
      "passiveName": "Courage",
      "passiveDesc": "On hit, Normal or Charged Attacks increase ATK by 6/7/8/9/10% for 6s. Max 4 stacks. Can only occur once every 0.5s.",
      "location": "Stuck inside a stone in Guyun Stone Forest",
      "ascensionMaterial": "aerosiderite",
      "id": "skyrider-greatsword"
  },
  {
      "name": "Skyrider Sword",
      "type": "Sword",
      "rarity": 3,
      "baseAttack": 38,
      "subStat": "Energy Recharge",
      "passiveName": "Determination",
      "passiveDesc": "Using an Elemental Burst grants a 12/15/18/21/24% increase in ATK and Movement SPD for 12s.",
      "location": "Gacha",
      "ascensionMaterial": "aerosiderite",
      "id": "skyrider-sword"
  },
  {
      "name": "Skyward Atlas",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 45,
      "subStat": "ATK",
      "passiveName": "Wandering Clouds",
      "passiveDesc": "Increases Elemental DMG Bonus by 12/15/18/21/24%. Normal Attack hits have a 50% chance to earn the favor of the clouds. which actively seek out nearby enemies to attack for 15s, dealing 160/200/240/280/320% ATK DMG. Can only occur once every 30s.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "skyward-atlas"
  },
  {
      "name": "Skyward Blade",
      "type": "Sword",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "Energy Recharge",
      "passiveName": "Sky-Piercing Fang",
      "passiveDesc": "CRIT Rate increased by 4%. Gains Skypiercing Might upon using an Elemental Burst:\nIncreases Movement SPD by 10%, increases ATK SPD by 10%, and increases the DMG of Normal and Charged Attack hits by 20% for 12s.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "skyward-blade"
  },
  {
      "name": "Skyward Harp",
      "type": "Bow",
      "rarity": 5,
      "baseAttack": 45,
      "subStat": "CRIT Rate",
      "passiveName": "Echoing Ballad",
      "passiveDesc": "Increases CRIT DMG by 20/25/30/35/40%. Hits have a 60/70/80/90/100% chance to inflict a small AoE attack, dealing 100% Physical ATK DMG. Can only occur once every 4s.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "skyward-harp"
  },
  {
      "name": "Skyward Pride",
      "type": "Claymore",
      "rarity": 5,
      "baseAttack": 45,
      "subStat": "Energy Recharge",
      "passiveName": "Sky-Ripping Dragon Spine",
      "passiveDesc": "Increases all DMG by 8/10/12/14/16%. After using an Elemental Burst, Normal or Charged Attack, on hit, creates a vacuum blade that does 80/100/120/140/160% Physical DMG to enemies along its path. Lasts for 20s or 8 vacuum blades.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "skyward-pride"
  },
  {
      "name": "Skyward Spine",
      "type": "Polearm",
      "rarity": 5,
      "baseAttack": 48,
      "subStat": "Energy Recharge",
      "passiveName": "Black Wing",
      "passiveDesc": "Increases CRIT Rate by 8% and increases Normal ATK SPD by 12%. Additionally, Normal and Charged Attacks hits on enemies have a 50% chance to trigger a vacuum blade that deals 40% of ATK as DMG in a small AoE. This effect can occur no more than once every 2s.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "skyward-spine"
  },
  {
      "name": "Slingshot",
      "type": "Bow",
      "rarity": 3,
      "baseAttack": 38,
      "subStat": "CRIT Rate",
      "passiveName": "Slingshot",
      "passiveDesc": "If a Normal Attack or Aimed Shot hits a target within 0.3s of being fired, increases DMG by 36/42/48/54/60%; otherwise, it decreases DMG by 10%.",
      "location": "Gacha",
      "ascensionMaterial": "guyun",
      "id": "slingshot"
  },
  {
      "name": "Snow-Tombed Starsilver",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Physical DMG Bonus",
      "passiveName": "Frost Burial",
      "passiveDesc": "Hitting an opponent with Normal and Charged Attacks has a 60% chance of forming and dropping an Everfrost Icicle above them, dealing 80% AoE ATK DMG. Opponents affected by Cryo are dealt 200% ATK DMG. Can only occur once every 10s.",
      "location": "Crafting",
      "ascensionMaterial": "decarabian",
      "id": "snow-tombed-starsilver"
  },
  {
      "name": "Solar Pearl",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT Rate",
      "passiveName": "Solar Shine",
      "passiveDesc": "Normal Attack hits increase Elemental Skill and Elemental Burst DMG by 20/25/30/35/40% for 6s. Likewise, Elemental Skill or Elemental Burst hits increase Normal Attack DMG by 20/25/30/35/40% for 6s.",
      "location": "BP Bounty",
      "ascensionMaterial": "guyun",
      "id": "solar-pearl"
  },
  {
      "name": "Song of Broken Pines",
      "type": "Claymore",
      "rarity": 5,
      "baseAttack": 49,
      "subStat": "Physical DMG Bonus",
      "passiveName": "Rebel's Banner Hymn",
      "passiveDesc": "A part of the 'Millennial Movement' that wanders amidst the winds. Increases ATK by 16%, and when Normal or Charged Attacks hit opponents, the character gains a Sigil of Whispers. This effect can be triggered once every 0.3s. When you possess four Sigils of 'Whispers, all of them will be consumed and all nearby party members will obtain the 'Millennial Movement: Banner-Hymn' effect for 12s. 'Millennial Movement: Banner-Hymn' increases Normal ATK SPD by 12% and increases ATK by 20%. Once this effect is triggered, you will not gain Sigils of Whispers for 20s. Of the many effects of the 'Millennial Movement', buffs of the same type will not stack.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "song-of-broken-pines"
  },
  {
      "name": "Song Of Stillness",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Benthic Pulse",
      "passiveDesc": "After the wielder is healed, they will deal 16% more DMG for 8s. This can be triggered even when the character is not on the field.",
      "location": "BP Bounty",
      "ascensionMaterial": "Fragment Of An Ancient Chord ",
      "id": "song-of-stillness"
  },
  {
      "name": "Splendor of Tranquil Waters",
      "type": "Sword",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "CRIT DMG",
      "passiveName": "Dawn and Dusk by the Lake",
      "passiveDesc": "When the equipping character's current HP increases or decreases, Elemental Skill DMG dealt will be increased by 8/10/12/14/16% for 6s. Max 3 stacks. This effect can be triggered once every 0.2s. When other party members' current HP increases or decreases, the equipping character's Max HP will be increased by 14/17.5/21/24.5/28% for 6s. Max 2 stacks. This effect can be triggered once every 0.2s. The aforementioned effects can be triggered even if the wielder is off-field.",
      "location": "Gacha",
      "ascensionMaterial": "pure-sacred-dewdrop",
      "id": "splendor-of-tranquil-waters"
  },
  {
      "name": "Staff of Homa",
      "type": "Polearm",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "CRIT DMG",
      "passiveName": "Reckless Cinnabar",
      "passiveDesc": "HP increased by 20/25/30/35/40%. Additionally, provides an ATK Bonus based on 0.8/1/1.2/1.4/1.6% of the wielder's Max HP. When the wielder's HP is less than 50%, this ATK Bonus is increased by an additional 1/1.2/1.4/1.6/1.8% of Max HP.",
      "location": "Gacha",
      "ascensionMaterial": "aerosiderite",
      "id": "staff-of-homa"
  },
  {
      "name": "Moonpiercer",
      "type": "Polearm",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "CRIT Rate",
      "passiveName": "Heat Haze at Horizon's End",
      "passiveDesc": "The equipping character gains 52% of their Elemental Mastery as bonus ATK. When an Elemental Skill hits opponents, the Dream of the Scarlet Sands effect will be gained for 10s: The equipping character will gain 28% of their Elemental Mastery as bonus ATK. Max 3 stacks.",
      "location": "Gacha",
      "ascensionMaterial": "oasis",
      "id": "staff-of-the-scarlet-sands"
  },
  {
      "name": "Summit Shaper",
      "type": "Sword",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "ATK",
      "passiveName": "",
      "passiveDesc": "Increases Shield Strength by 20/25/30/35/40%. Scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.",
      "location": "Gacha",
      "ascensionMaterial": "guyun",
      "id": "summit-shaper"
  },
  {
      "name": "Sword of Descension",
      "type": "Sword",
      "rarity": 4,
      "BaseAttack": 39,
      "subStat": "ATK",
      "passiveName": "Descension",
      "passiveDesc": "Hitting enemies with Normal or Charged Attacks grants a 50% chance to deal 200% ATK as DMG in a small AoE. This effect can only occur once every 10s. Additionally, if the Traveler equips the Sword of Descension, their ATK is increased by 66.",
      "location": "Given via the Mail on PS4/PS5, obtainable on PC/Mobile via cross save",
      "ascensionMaterial": "boreal",
      "id": "sword-of-descension"
  },
  {
      "name": "Talking Stick",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "CRIT Rate",
      "passiveName": "The Silver Tongue",
      "passiveDesc": "ATK will be increased by 16% for 15s after being affected by Pyro. This effect can be triggered once every 12s. All Elemental DMG Bonus will be increased by 12% for 15s after being affected by Hydro, Cryo, Electro, or Dendro. This effect can be triggered once every 12s.",
      "location": "BP Bounty",
      "ascensionMaterial": "Oasis Garden’s Reminiscence ",
      "id": "talking-stick"
  },
  {
      "name": "The Alley Flash",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "CRIT Rate",
      "passiveName": "Itinerant Hero",
      "passiveDesc": "Continuosly sprinting for at least 1s increases ATK by 28% for 6s. This effect cannot stack.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "the-alley-flash"
  },
  {
      "name": "The Bell",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "HP",
      "passiveName": "Rebellious Guardian",
      "passiveDesc": "Taking DMG generates a shield which absorbs DMG up to 20/23/26/29/32% of Max HP. This shield lasts for 10s or until broken, and can only be triggered once every 45s. While protected by the shield, the character gains 12/15/18/21/24% increased DMG.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "the-bell"
  },
  {
      "name": "The Black Sword",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT Rate",
      "passiveName": "Justice",
      "passiveDesc": "Increases DMG dealt by Normal and Charged Attacks by 20%.\nAdditionally, regenerates 60% of ATK as HP when Normal and Charged Attacks score a CRIT Hit. This effect can occur once every 5s.",
      "location": "BP Bounty",
      "ascensionMaterial": "boreal",
      "id": "the-black-sword"
  },
  {
      "name": "The Catch",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Shanty",
      "passiveDesc": "Increases Elemental Burst DMG by 16/20/24/28/32% and Elemental Burst CRIT Rate by 6/7.5/9/10.5/12%.",
      "location": "Inazuma Fishing Association",
      "id": "the-catch"
  },
  {
      "name": "The Dockhand's Assistant",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "HP",
      "passiveName": "Sea Shanty",
      "passiveDesc": "When the wielder is healed or heals others, they will gain a Stoic's Symbol that lasts 30s, up to a maximum of 3 Symbols. When using their Elemental Skill or Burst, all Symbols will be consumed and the Roused effect will be granted for 10s. For each Symbol consumed, gain 40/50/60/70/80 Elemental Mastery, and 2s after the effect occurs, 2/2.5/3/3.5/4 Energy per Symbol consumed will be restored for said character. The Roused effect can be triggered once every 15s, and Symbols can be gained even when the character is not on the field.",
      "location": "Gacha",
      "ascensionMaterial": "pure-sacred-dewdrop",
      "id": "the-dockhands-assistant"
  },
  {
      "name": "The First Great Magic",
      "type": "Bow",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "CRIT DMG",
      "passiveName": "Parsifal the Great",
      "passiveDesc": "DMG dealt by Charged Attacks increased by 16%. For every party member with the same Elemental Type as the wielder (including the wielder themselves), gain 1 Gimmick stack. For every party member with a different Elemental Type from the wielder, gain 1 Theatrics stack. When the wielder has 1/2/3 or more Gimmick stacks, ATK will be increased by 16%/32%/48%. When the wielder has 1/2/3 or more Theatrics stacks, Movement SPD will be increased by 4%/7%/10%.",
      "location": "Gacha",
      "ascensionMaterial": "Fragment Of An Ancient Chord",
      "id": "the-first-great-magic"
  },
  {
      "name": "The Flute",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "Chord",
      "passiveDesc": "Normal or Charged Attacks grant Harmonic on hits. Gaining 5 Harmonics triggers the power of music and deals 100/125/150/175/200% ATK DMG to surrounding enemies. Harmonics last up to 30s, and a maximum of 1 can be gained every 0.5s.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "the-flute"
  },
  {
      "name": "The Stringless",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Elemental Mastery",
      "passiveName": "Arrowless Song",
      "passiveDesc": "Increases Elemental Skill and Elemental Burst DMG by 24/30/36/42/48%.",
      "location": "Gacha",
      "ascensionMaterial": "decarabian",
      "id": "the-stringless"
  },
  {
      "name": "The Unforged",
      "type": "Claymore",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "ATK",
      "passiveName": "Golden Majesty",
      "passiveDesc": "Increases Shield Strength by 20/25/30/35/40%, scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield this ATK increase effect is increased by 100%",
      "location": "Gacha",
      "id": "the-unforged"
  },
  {
      "name": "The Viridescent Hunt",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT Rate",
      "passiveName": "Verdant Wind",
      "passiveDesc": "Upon hit, Normal and Aimed Shot Attacks have a 50% chance to generate a Cyclone, which will continuously attract surrounding enemies, dealing 40% of ATK as DMG to these enemies every 0.5s for 4s. This effect can only occur once every 14s.",
      "location": "BP Bounty",
      "ascensionMaterial": "decarabian",
      "id": "the-viridescent-hunt"
  },
  {
      "name": "The Widsith",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT DMG",
      "passiveName": "Debut",
      "passiveDesc": "When the character takes the field, they gain a random theme song for 10s:\nRecitative: Increases Base ATK by 60%\nInterlude: Elemental Mastery is increased by 240\nAria: Increases all Elemental DMG by 48%\nCan only occur once every 30s",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "the-widsith"
  },
  {
      "name": "Thrilling Tales of Dragon Slayers",
      "type": "Catalyst",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "HP",
      "passiveName": "Legacy",
      "passiveDesc": "When switching characters, the new character taking the field has their ATK increased by 24/30/36/42/48% for 10s. This effect can only occur once every 20s.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "thrilling-tales-of-dragon-slayers"
  },
  {
      "name": "Thundering Pulse",
      "type": "Bow",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "CRIT DMG",
      "passiveName": "Rule By Thunder",
      "passiveDesc": "Increases ATK by 20% and grants the might of the Thunder Emblem. At stack levels 1/2/3, the Thunder Emblem increases Normal Attack DMG by 12/24/40%. The character will obtain 1 stack of Thunder Emblem in each of the following scenarios: Normal Attack deals DMG (stack lasts 5s), casting Elemental Skill (stack lasts 10s); Energy is less than 100% (stack disappears when Energy is full). Each stack's duration is calculated independently.",
      "location": "Gacha",
      "ascensionMaterial": "narukami",
      "id": "thundering-pulse"
  },
  {
      "name": "Tidal Shadow",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "ATK",
      "passiveName": "White Cruising Wave",
      "passiveDesc": "After the wielder is healed, ATK will be increased by 24% for 8s. This can be triggered even when the character is not on the field.",
      "location": "BP Bounty",
      "ascensionMaterial": "Broken Goblet Of The Pristine Sea",
      "id": "tidal-shadow"
  },
  {
      "name": "Tome of the Eternal Flow",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "CRIT DMG",
      "passiveName": "Aeon Wave",
      "passiveDesc": "HP is increased by 16/20/24/28/32%. When current HP increases or decreases, Charged Attack DMG will be increased by 14/18/22/26/30% for 4s. Max 3 stacks, can be triggered once every 0.3s. When you have 3 stacks or refresh a third stack's duration, 8/9/10/11/12 Energy will be restored. This Energy restoration effect can be triggered once every 12s.",
      "location": "Gacha",
      "ascensionMaterial": "pure-sacred-dewdrop",
      "id": "tome-of-the-eternal"
  },
  {
      "name": "Toukabou Shigure",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Elemental Mastery",
      "passiveName": "Kaidan: Rainfall Earthbinder",
      "passiveDesc": "After an attack hits opponents, it will inflict an instance of Cursed Parasol upon one of them for 10s. This effect can be triggered once every 15s. If this opponent is defeated during Cursed Parasol's duration, Cursed Parasol's CD will be refreshed immediately. The character wielding this weapon will deal 16/20/24/28/32% more DMG to the opponent affected by Cursed Parasol.",
      "location": "Akitsu Kimodameshi Event",
      "ascensionMaterial": "narukami",
      "id": "toukabou-shigure"
  },
  {
      "name": "Traveler's Handy Sword",
      "type": "Sword",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "DEF",
      "passiveName": "Journey",
      "passiveDesc": "Each Elemental Orb or Particle collected restores 1/1.25/1.5/1.75/2% HP.",
      "location": "Chest",
      "ascensionMaterial": "dandelion",
      "id": "traveler-s-handy-sword"
  },
  {
      "name": "Tulaytullah's Remembrance",
      "type": "Catalyst",
      "rarity": 5,
      "baseAttack": 48,
      "subStat": "CRIT DMG",
      "passiveName": "Bygone Azure Teardrop",
      "passiveDesc": "Normal Attack SPD is increased by 10%. After the wielder unleashes an Elemental Skill, Normal Attack DMG will increase by 4.8% every second for 14s. After this character hits an opponent with a Normal Attack during this duration, Normal Attack DMG will be increased by 9.6%. This increase can be triggered once every 0.3s.",
      "location": "Gacha",
      "ascensionMaterial": "Echo of Scorching Might",
      "id": "tulaytullah-s-remembrance"
  },
  {
      "name": "Twin Nephrite",
      "type": "Catalyst",
      "rarity": 3,
      "baseAttack": 40,
      "subStat": "CRIT Rate",
      "passiveName": "Guerilla Tactic",
      "passiveDesc": "Defeating an enemy increases Movement SPD and ATK by 12/14/16/18/20% for 15s.",
      "location": "Chests",
      "ascensionMaterial": "elixir",
      "id": "twin-nephrite"
  },
  {
      "name": "Ultimate Overlord's Mega Magic Sword",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 44,
      "subStat": "Energy Recharge",
      "passiveName": "Melussistance!",
      "passiveDesc": "ATK increased by 12/15/18/21/24%. That's not all! The support from all Melusines you've helped in Merusea Village fills you with strength! Based on the number of them you've helped, your ATK is increased by up to an additional 12/15/18/21/24%.",
      "location": "Event: Roses and Muskets",
      "ascensionMaterial": "pristine-sea",
      "id": "ultimate-overlord-s-mega-magic-sword"
  },
  {
      "name": "Uraku Misugiri",
      "type": "Sword",
      "rarity": 5,
      "baseAttack": 44,
      "subStat": "CRIT DMG",
      "passiveName": "Brocade Bloom, Shrine Sword",
      "passiveDesc": "Normal Attack DMG is increased by 16/20/24/28/32% and Elemental Skill DMG is increased by 24/30/36/42/48%. After a nearby active character deals Geo DMG, the aforementioned effects increase by 100% for 15s. Additionally, the wielder's DEF is increased by 20/25/30/35/40%.",
      "location": "Gacha",
      "ascensionMaterial": "distantant-sea",
      "id": "uraku-misugiri"
  },
  {
      "name": "Verdict",
      "type": "Claymore",
      "rarity": 5,
      "baseAttack": 48,
      "subStat": "CRIT Rate",
      "passiveName": "Many Oaths of Dawn and Dusk",
      "passiveDesc": "Increases ATK by 20/25/30/35/40%. When characters in your party obtain Elemental Shards from Crystallize reactions, the equipping character will gain 1 Seal, increasing Elemental Skill DMG by 18/22.5/27/31.5/36%. The Seal lasts for 15s, and the equipped may have up to 2 Seals at once. All of the equipper's Seals will disappear 0.2s after their Elemental Skill deals DMG.",
      "location": "Gacha",
      "ascensionMaterial": "ancient-chord",
      "id": "verdict"
  },
  {
      "name": "Vortex Vanquisher",
      "type": "Polearm",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "ATK",
      "passiveName": "Golden Majesty",
      "passiveDesc": "Increases Shield Strength by 20/25/30/35/40%, scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield this ATK increase effect is increased by 100%",
      "location": "Gacha",
      "ascensionMaterial": "aerosiderite",
      "id": "vortex-vanquisher"
  },
  {
      "name": "Wandering Evenstar",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Elemental Mastery",
      "passiveName": "Wildling Nightstar",
      "passiveDesc": "The following effect will trigger every 10s: The equipping character will gain 24% of their Elemental Mastery as bonus ATK for 12s, with nearby party members gaining 30% of this buff for the same duration. Multiple instances of this weapon can allow this buff to stack. This effect will still trigger even if the character is not on the field.",
      "location": "Gacha",
      "ascensionMaterial": "oasis",
      "id": "wandering-evenstar"
  },
  {
      "name": "Waster Greatsword",
      "type": "Claymore",
      "rarity": 1,
      "baseAttack": 23,
      "subStat": "-",
      "passiveName": "-",
      "passiveDesc": "-",
      "location": "Chest",
      "ascensionMaterial": "boreal",
      "id": "waster-greatsword"
  },
  {
      "name": "Wavebreaker's Fin",
      "type": "Polearm",
      "rarity": 4,
      "baseAttack": 45,
      "subStat": "ATK",
      "passiveName": "Watatsumi Wavewalker",
      "passiveDesc": "For every point of the entire party's combined maximum Energy capacity, the Elemental Burst DMG of the character equipping this weapon is increased by 0.12/0.15/0.18/0.21/0.24%. A maximum of 40/50/60/70/80% increased Elemental Burst DMG can be achieved this way.",
      "location": "Gacha",
      "ascensionMaterial": "mask",
      "id": "wavebreaker-s-fin"
  },
  {
      "name": "White Iron Greatsword",
      "type": "Claymore",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "DEF",
      "passiveName": "Cull the Weak",
      "passiveDesc": "Defeating an opponent restores 8/10/12/14/16% HP.",
      "location": "Chests",
      "ascensionMaterial": "dandelion",
      "id": "white-iron-greatsword"
  },
  {
      "name": "White Tassel",
      "type": "Polearm",
      "rarity": 3,
      "baseAttack": 39,
      "subStat": "CRIT Rate",
      "passiveName": "Sharp",
      "passiveDesc": "Increases Normal Attack DMG by 24/30/36/42/48%.",
      "location": "Chest",
      "ascensionMaterial": "guyun",
      "id": "white-tassel"
  },
  {
      "name": "Whiteblind",
      "type": "Claymore",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "DEF",
      "passiveName": "Infusion Blade",
      "passiveDesc": "On hit, Normal or Charged Attacks increase Base ATK and DEF by 6/7.5/9/10.5/12% for 6s. Max 4 stacks. Can only occur once every 0.5s.",
      "location": "Crafting",
      "ascensionMaterial": "guyun",
      "id": "whiteblind"
  },
  {
      "name": "Windblume Ode",
      "type": "Bow",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Elemental Mastery",
      "passiveName": "Windblume Wish",
      "passiveDesc": "After using an Elemental Skill, receive a boon from the ancient wish of the Windblume, increasing ATK by 16/20/24/28/32% for 6s.",
      "location": "Invitation to Windblume (v1.4) Event Shop",
      "ascensionMaterial": "dandelion",
      "id": "windblume-ode"
  },
  {
      "name": "Wine and Song",
      "type": "Catalyst",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Energy Recharge",
      "passiveName": "Wind in the Square",
      "passiveDesc": "For every character in the party who hails from Mondstadt, the character who equips this weapon gains 8/10/12/14/16% ATK increase and 3/3.5/4/4.5/5% Movement SPD increase.",
      "location": "Gacha",
      "ascensionMaterial": "boreal",
      "id": "wine-and-song"
  },
  {
      "name": "Wolf-Fang",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "CRIT Rate",
      "passiveName": "Northwind Wolf",
      "passiveDesc": "DMG dealt by Elemental Skill and Elemental Burst is increased by 16%. When an Elemental Skill hits an opponent, its CRIT Rate will be increased by 2%. When an Elemental Burst hits an opponent, its CRIT Rate will be increased by 2%. Both of these effects last 10s separately, have 4 max stacks, and can be triggered once every 0.1s.",
      "location": "BP Bounty",
      "ascensionMaterial": "Fragment Of An Ancient Chord",
      "id": "wolf-fang"
  },
  {
      "name": "Wolf's Gravestone",
      "type": "Claymore",
      "rarity": 5,
      "baseAttack": 46,
      "subStat": "ATK",
      "passiveName": "Wolfish Tracker",
      "passiveDesc": "Increases Base ATK by 20/25/30/35/40%. On hit, attacks against enemies with less than 30% HP increase all party members' Base ATK by 40/50/60/70/80% for 12s. Can only occur once every 30s.",
      "location": "Gacha",
      "ascensionMaterial": "dandelion",
      "id": "wolf-s-gravestone"
  },
  {
      "name": "Xiphos' Moonlight",
      "type": "Sword",
      "rarity": 4,
      "baseAttack": 42,
      "subStat": "Elemental Mastery",
      "passiveName": "Jinni's Whisper",
      "passiveDesc": "The following effect will trigger every 10s: The equipping character will gain 0.036% Energy Recharge for each point of Elemental Mastery they possess for 12s, with nearby party members gaining 30% of this buff for the same duration. Multiple instances of this weapon can allow this buff to stack. This effect will still trigger even if the character is not on the field.",
      "location": "Gacha",
      "ascensionMaterial": "talisman",
      "id": "xiphos-moonlight"
  }
]